#
#    MedCEP - A powerful tool for measure
#    
#    Copyright (C) 2013 Ciro Xavier Maretto
#    Copyright (C) 2015 Henrique Néspoli Castro, Vinícius Soares Fonseca                          
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/lgpl.html>.    
#

java.naming.factory.initial=org.jnp.interfaces.NamingContextFactory
java.naming.provider.url=localhost:10666
java.naming.factory.url.pkgs=org.jboss.naming
